# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from proto import pdosd_pb2 as proto_dot_pdosd__pb2


class PDOSDStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.OperationList = channel.unary_stream(
        '/PDOSD/OperationList',
        request_serializer=proto_dot_pdosd__pb2.Empty.SerializeToString,
        response_deserializer=proto_dot_pdosd__pb2.Operation.FromString,
        )
    self.OperationPropose = channel.unary_unary(
        '/PDOSD/OperationPropose',
        request_serializer=proto_dot_pdosd__pb2.OperationProposeOptions.SerializeToString,
        response_deserializer=proto_dot_pdosd__pb2.OperationProposeResult.FromString,
        )
    self.OperationJoin = channel.unary_unary(
        '/PDOSD/OperationJoin',
        request_serializer=proto_dot_pdosd__pb2.OperationJoinOptions.SerializeToString,
        response_deserializer=proto_dot_pdosd__pb2.OperationJoinResult.FromString,
        )


class PDOSDServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def OperationList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OperationPropose(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OperationJoin(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PDOSDServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'OperationList': grpc.unary_stream_rpc_method_handler(
          servicer.OperationList,
          request_deserializer=proto_dot_pdosd__pb2.Empty.FromString,
          response_serializer=proto_dot_pdosd__pb2.Operation.SerializeToString,
      ),
      'OperationPropose': grpc.unary_unary_rpc_method_handler(
          servicer.OperationPropose,
          request_deserializer=proto_dot_pdosd__pb2.OperationProposeOptions.FromString,
          response_serializer=proto_dot_pdosd__pb2.OperationProposeResult.SerializeToString,
      ),
      'OperationJoin': grpc.unary_unary_rpc_method_handler(
          servicer.OperationJoin,
          request_deserializer=proto_dot_pdosd__pb2.OperationJoinOptions.FromString,
          response_serializer=proto_dot_pdosd__pb2.OperationJoinResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PDOSD', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
