# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/pdosd.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/pdosd.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11proto/pdosd.proto\"\x07\n\x05\x45mpty\"\xc8\x01\n\tOperation\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x11\n\tthreshold\x18\x02 \x01(\x04\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x0f\n\x07service\x18\x04 \x01(\t\x12\x13\n\x0b\x65poch_start\x18\x05 \x01(\x04\x12\x12\n\nepoch_stop\x18\x06 \x01(\x04\x12\x0f\n\x07staking\x18\x07 \x01(\x04\x12\x0c\n\x04info\x18\x08 \x01(\t\x12\r\n\x05users\x18\t \x01(\x04\x12\x0f\n\x07\x64\x65\x63ided\x18\n \x01(\x08\x12\x0e\n\x06joined\x18\x0b \x01(\x08\"\'\n\x14OperationJoinOptions\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"I\n\x13OperationJoinResult\x12\x1d\n\toperation\x18\x01 \x01(\x0b\x32\n.Operation\x12\x13\n\x0btransaction\x18\x02 \x01(\t\"\x95\x01\n\x17OperationProposeOptions\x12\x11\n\tthreshold\x18\x01 \x01(\x04\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x0f\n\x07service\x18\x03 \x01(\t\x12\x13\n\x0b\x65poch_start\x18\x04 \x01(\x04\x12\x12\n\nepoch_stop\x18\x05 \x01(\x04\x12\x0f\n\x07staking\x18\x06 \x01(\x04\x12\x0c\n\x04info\x18\x07 \x01(\t\"L\n\x16OperationProposeResult\x12\x1d\n\toperation\x18\x01 \x01(\x0b\x32\n.Operation\x12\x13\n\x0btransaction\x18\x02 \x01(\t2\xb9\x01\n\x05PDOSD\x12\'\n\rOperationList\x12\x06.Empty\x1a\n.Operation\"\x00\x30\x01\x12G\n\x10OperationPropose\x12\x18.OperationProposeOptions\x1a\x17.OperationProposeResult\"\x00\x12>\n\rOperationJoin\x12\x15.OperationJoinOptions\x1a\x14.OperationJoinResult\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=28,
)


_OPERATION = _descriptor.Descriptor(
  name='Operation',
  full_name='Operation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='Operation.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threshold', full_name='Operation.threshold', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='Operation.target', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='Operation.service', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_start', full_name='Operation.epoch_start', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_stop', full_name='Operation.epoch_stop', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staking', full_name='Operation.staking', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='Operation.info', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='Operation.users', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decided', full_name='Operation.decided', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='joined', full_name='Operation.joined', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=231,
)


_OPERATIONJOINOPTIONS = _descriptor.Descriptor(
  name='OperationJoinOptions',
  full_name='OperationJoinOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='OperationJoinOptions.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=272,
)


_OPERATIONJOINRESULT = _descriptor.Descriptor(
  name='OperationJoinResult',
  full_name='OperationJoinResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='OperationJoinResult.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='OperationJoinResult.transaction', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=274,
  serialized_end=347,
)


_OPERATIONPROPOSEOPTIONS = _descriptor.Descriptor(
  name='OperationProposeOptions',
  full_name='OperationProposeOptions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='threshold', full_name='OperationProposeOptions.threshold', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='OperationProposeOptions.target', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='OperationProposeOptions.service', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_start', full_name='OperationProposeOptions.epoch_start', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='epoch_stop', full_name='OperationProposeOptions.epoch_stop', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='staking', full_name='OperationProposeOptions.staking', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='info', full_name='OperationProposeOptions.info', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=499,
)


_OPERATIONPROPOSERESULT = _descriptor.Descriptor(
  name='OperationProposeResult',
  full_name='OperationProposeResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='OperationProposeResult.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transaction', full_name='OperationProposeResult.transaction', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=577,
)

_OPERATIONJOINRESULT.fields_by_name['operation'].message_type = _OPERATION
_OPERATIONPROPOSERESULT.fields_by_name['operation'].message_type = _OPERATION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Operation'] = _OPERATION
DESCRIPTOR.message_types_by_name['OperationJoinOptions'] = _OPERATIONJOINOPTIONS
DESCRIPTOR.message_types_by_name['OperationJoinResult'] = _OPERATIONJOINRESULT
DESCRIPTOR.message_types_by_name['OperationProposeOptions'] = _OPERATIONPROPOSEOPTIONS
DESCRIPTOR.message_types_by_name['OperationProposeResult'] = _OPERATIONPROPOSERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'proto.pdosd_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Operation = _reflection.GeneratedProtocolMessageType('Operation', (_message.Message,), {
  'DESCRIPTOR' : _OPERATION,
  '__module__' : 'proto.pdosd_pb2'
  # @@protoc_insertion_point(class_scope:Operation)
  })
_sym_db.RegisterMessage(Operation)

OperationJoinOptions = _reflection.GeneratedProtocolMessageType('OperationJoinOptions', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONJOINOPTIONS,
  '__module__' : 'proto.pdosd_pb2'
  # @@protoc_insertion_point(class_scope:OperationJoinOptions)
  })
_sym_db.RegisterMessage(OperationJoinOptions)

OperationJoinResult = _reflection.GeneratedProtocolMessageType('OperationJoinResult', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONJOINRESULT,
  '__module__' : 'proto.pdosd_pb2'
  # @@protoc_insertion_point(class_scope:OperationJoinResult)
  })
_sym_db.RegisterMessage(OperationJoinResult)

OperationProposeOptions = _reflection.GeneratedProtocolMessageType('OperationProposeOptions', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONPROPOSEOPTIONS,
  '__module__' : 'proto.pdosd_pb2'
  # @@protoc_insertion_point(class_scope:OperationProposeOptions)
  })
_sym_db.RegisterMessage(OperationProposeOptions)

OperationProposeResult = _reflection.GeneratedProtocolMessageType('OperationProposeResult', (_message.Message,), {
  'DESCRIPTOR' : _OPERATIONPROPOSERESULT,
  '__module__' : 'proto.pdosd_pb2'
  # @@protoc_insertion_point(class_scope:OperationProposeResult)
  })
_sym_db.RegisterMessage(OperationProposeResult)



_PDOSD = _descriptor.ServiceDescriptor(
  name='PDOSD',
  full_name='PDOSD',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=580,
  serialized_end=765,
  methods=[
  _descriptor.MethodDescriptor(
    name='OperationList',
    full_name='PDOSD.OperationList',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_OPERATION,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OperationPropose',
    full_name='PDOSD.OperationPropose',
    index=1,
    containing_service=None,
    input_type=_OPERATIONPROPOSEOPTIONS,
    output_type=_OPERATIONPROPOSERESULT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='OperationJoin',
    full_name='PDOSD.OperationJoin',
    index=2,
    containing_service=None,
    input_type=_OPERATIONJOINOPTIONS,
    output_type=_OPERATIONJOINRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PDOSD)

DESCRIPTOR.services_by_name['PDOSD'] = _PDOSD

# @@protoc_insertion_point(module_scope)
